In [1]:
# csv파일로 저장
# DataFrame객체.to_csv("이름")

import pandas as pd 

data = {
    'name' : [ 'Jerry', 'Riah', 'Paul'],
    'algol' : [ "A", "A+", "B"],
    'basic' : [ "C", "B", "B+"],
    'c++' : [ "B+", "C", "C+"],
}

df = pd.DataFrame(data)
df.set_index("name")

df

    name algol basic c++
0  Jerry     A     C  B+
1   Riah    A+     B   C
2   Paul     B    B+  C+

In [2]:
df.to_csv("./data/df_sample.csv")

In [3]:
df

    name algol basic c++
0  Jerry     A     C  B+
1   Riah    A+     B   C
2   Paul     B    B+  C+

In [4]:
df.to_csv("./data/df_sample_no_index.csv", index=False)