In [1]:
import pandas as pd

In [2]:
fruit_names = pd.Series([
    "Apple", "Banana", "Cherry"
])

fruit_names

0     Apple
1    Banana
2    Cherry
dtype: object

In [3]:
pd.Series([
    "Apple", "Banana", "Cherry"
], dtype="string")

0     Apple
1    Banana
2    Cherry
dtype: string

In [4]:
pd.Series([
    "Apple", "Banana", "Cherry"
], dtype=pd.StringDtype())

0     Apple
1    Banana
2    Cherry
dtype: string

In [6]:
fruit_names.astype("string")

0     Apple
1    Banana
2    Cherry
dtype: string

In [8]:
# 문자열 매서드 
import pandas as pd
import numpy as np 

ser = pd.Series([
    "Apple_사과", "Banana_바나나", "Cherry_체리", np.nan
], index=["First ", " Second", " Third", "Fourth"])

ser

ser2 = pd.Series([
    "Apple_사과", "Banana_바나나", "Cherry_체리", np.nan
], index=["First ", " Second", " Third", "Fourth"], dtype="string")

ser2

First        Apple_사과
 Second    Banana_바나나
 Third      Cherry_체리
Fourth           <NA>
dtype: string

In [12]:
print(ser.str.lower())
print(ser.str.upper())
print(ser.str.len())

First        apple_사과
 Second    banana_바나나
 Third      cherry_체리
Fourth            NaN
dtype: object
First        APPLE_사과
 Second    BANANA_바나나
 Third      CHERRY_체리
Fourth            NaN
dtype: object
First       8.0
 Second    10.0
 Third      9.0
Fourth      NaN
dtype: float64

In [13]:
ser

First        Apple_사과
 Second    Banana_바나나
 Third      Cherry_체리
Fourth            NaN
dtype: object

In [14]:
result1 = ser.str.split("_")
result1

First        [Apple, 사과]
 Second    [Banana, 바나나]
 Third      [Cherry, 체리]
Fourth               NaN
dtype: object

In [15]:
result2 = ser.str.split("_", expand=True)
result2

              0    1
First     Apple   사과
 Second  Banana  바나나
 Third   Cherry   체리
Fourth      NaN  NaN

In [17]:
ser.str.split("_").str.get(0)

First       Apple
 Second    Banana
 Third     Cherry
Fourth        NaN
dtype: object

In [21]:
# 문자열 매서도 

idx = ser.index

print(idx)
print(idx.str.strip())

Index(['First ', ' Second', ' Third', 'Fourth'], dtype='object')
Index(['First', 'Second', 'Third', 'Fourth'], dtype='object')

In [22]:
print(ser.str.replace("_", ":", regex=False))

First        Apple:사과
 Second    Banana:바나나
 Third      Cherry:체리
Fourth            NaN
dtype: object

In [23]:
ser.str.replace("[^a-zA-Z\s]", "", regex=True)

First       Apple
 Second    Banana
 Third     Cherry
Fourth        NaN
dtype: object

In [24]:
print(ser.str[0])

First        A
 Second      B
 Third       C
Fourth     NaN
dtype: object

In [25]:
ser.str[0:4]

First      Appl
 Second    Bana
 Third     Cher
Fourth      NaN
dtype: object

In [26]:
ser.str.contains("A", na=False)

First       True
 Second    False
 Third     False
Fourth     False
dtype: bool

In [27]:
ser.str.contains(r"[A|B][a-z]*")

First       True
 Second     True
 Third     False
Fourth       NaN
dtype: object

In [28]:
ser.str.fullmatch(r"[A|B][a-z]*")

First      False
 Second    False
 Third     False
Fourth       NaN
dtype: object

In [29]:
ser3 = pd.Series([
    "a1", "b2", "c3", "d4a5", "e6e7", "f8"
], dtype="string")
ser3

0      a1
1      b2
2      c3
3    d4a5
4    e6e7
5      f8
dtype: string

In [34]:
ser3.str.extractall(r"(\d)").groupby(level=0).agg("".join)

    0
0   1
1   2
2   3
3  45
4  67
5   8

In [36]:
ser3.str.extractall(r"([a-z])").groupby(level=0).agg("".join)

    0
0   a
1   b
2   c
3  da
4  ee
5   f

In [38]:
# 숫자랑 필드랑 컬럼으로 분리 
ser3.str.extract(r"(?P<Letter>[a-z]+)(?P<Digit>\d+)")

  Letter Digit
0      a     1
1      b     2
2      c     3
3      d     4
4      e     6
5      f     8